ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS avatar TEXT,
  ADD COLUMN IF NOT EXISTS rank_points INTEGER DEFAULT 1000,
  ADD COLUMN IF NOT EXISTS coins NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

ALTER TABLE IF EXISTS matches
  ADD COLUMN IF NOT EXISTS server_id TEXT,
  ADD COLUMN IF NOT EXISTS map TEXT,
  ADD COLUMN IF NOT EXISTS team_a_players TEXT[],
  ADD COLUMN IF NOT EXISTS team_b_players TEXT[],
  ADD COLUMN IF NOT EXISTS winner_team TEXT,
  ADD COLUMN IF NOT EXISTS match_start TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS match_end TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS match_stats
  ADD COLUMN IF NOT EXISTS steamId TEXT,
  ADD COLUMN IF NOT EXISTS assists INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS hs INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS clutch INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS adr REAL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS score INTEGER DEFAULT 0;

CREATE TABLE IF NOT EXISTS server_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  status TEXT NOT NULL,
  gcp_instance_id TEXT,
  players TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ac_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  steamId TEXT,
  match_id UUID REFERENCES matches(id) ON DELETE CASCADE,
  type TEXT,
  details JSONB,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  steamId TEXT,
  amount NUMERIC(12,2) NOT NULL,
  type TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS leaderboard (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  steamId TEXT UNIQUE,
  points INTEGER DEFAULT 0,
  weekly_points INTEGER DEFAULT 0,
  monthly_points INTEGER DEFAULT 0
);